### PR TITLE
Return 201 status code

### PR DESCRIPTION
**Pull request by krishnaindani**
Issue: https://github.com/iliafrenkel/go-pb/issues/1
- Return the 201 status code on the creation and add `Location` to the header.

### CODE REVIEW

**Comment by iliafrenkel** [comment]
Thank you, @krishnaindani for your contribution!

**Comment by krishnaindani** [comment]
You're Welcome. Thank you so much for letting me contribute. I would like to contribute more if you got any ideas and tasks breakouts as I guess the project is in the initial phase.

**Comment by iliafrenkel** [comment]
I have plenty of ideas! I need to set the structure of the project right, I don't like the way it is now. Once I do that it will be much easier for multiple people to work on the project and I will start creating "feature" issues. WIll probably need a few days though.

**Comment by krishnaindani** [comment]
That sounds great. Would you tag me or update me once you have the setup?  I will keep an eye on the project as well.

**Comment by iliafrenkel** [comment]
Sure! I'll let you know.

**Comment by krishnaindani** [comment]
> Sure! I'll let you know.

Thank you so much!!

**Pull request merged**
